<?php

declare(strict_types=1);

namespace Src\Admin\Blog\Infrastructure\Repositories;

use Illuminate\Support\Facades\DB;
use Src\Admin\Blog\Domain\Contracts\BlogRepositoryContract;
use Src\Admin\Blog\Domain\Entity\Blog;
use Src\Admin\Blog\Domain\Entity\BlogTranslation;
use Src\Admin\Blog\Infrastructure\Models\BlogEloquentModel;
use Src\Admin\Blog\Infrastructure\Models\BlogTranslationEloquentModel;

final class EloquentBlogRepository implements BlogRepositoryContract
{
    private BlogEloquentModel $model;

    public function __construct(BlogEloquentModel $model)
    {
        $this->model = $model;
    }

    public function save(Blog $blog): int
    {
        $blogId = 0;

        DB::transaction(function () use ($blog, &$blogId) {
            $eloquentBlog = $this->model->create([
                'user_id' => $blog->userId(),
                'image' => $blog->image(),
                'category_code' => $blog->categoryCode(),
                'writer' => $blog->writer(),
                'views' => $blog->views(),
                'status' => $blog->status(),
                'published_at' => $blog->publishedAt(),
                'notification_sent_at' => $blog->notificationSentAt(),
            ]);

            $blogId = $eloquentBlog->id;

            foreach ($blog->translations() as $translation) {
                $eloquentBlog->translations()->create([
                    'lang' => $translation->lang(),
                    'title' => $translation->title(),
                    'content' => $translation->content()
                    // slug se genera automáticamente por Spatie HasSlug
                ]);
            }
        });

        return $blogId;
    }

    public function updateImage(int $id, string $imagePath): void
    {
        $eloquentBlog = $this->model->find($id);
        if ($eloquentBlog) {
            $eloquentBlog->update(['image' => $imagePath]);
        }
    }


    public function findById(int $id): ?Blog
    {
        $eloquentBlog = $this->model->with('translations')->find($id);

        if (!$eloquentBlog) {
            return null;
        }

        return $this->toDomainEntity($eloquentBlog);
    }

    public function findBySlug(string $slug, string $lang): ?Blog
    {
        $translationModel = BlogTranslationEloquentModel::where('slug', $slug)
            ->where('lang', $lang)
            ->first();

        if (!$translationModel) {
            return null;
        }

        $eloquentBlog = $this->model->with(['translations' => function ($query) use ($lang) {
            $query->where('lang', $lang);
        }])->find($translationModel->blog_id);

        if (!$eloquentBlog) {
            return null;
        }

        return $this->toDomainEntity($eloquentBlog);
    }

    public function update(Blog $blog): void
    {
        if ($blog->id() === null) {
            return;
        }

        DB::transaction(function () use ($blog) {
            $eloquentBlog = $this->model->find($blog->id());
            
            if ($eloquentBlog) {
                $eloquentBlog->update([
                    'user_id' => $blog->userId(),
                    'image' => $blog->image(),
                    'category_code' => $blog->categoryCode(),
                    'writer' => $blog->writer(),
                    'views' => $blog->views(),
                    'status' => $blog->status(),
                    'published_at' => $blog->publishedAt(),
                    'notification_sent_at' => $blog->notificationSentAt(),
                ]);

                // Sync Translations: delete and recreate (slugs auto-generated by Spatie)
                $eloquentBlog->translations()->delete();
                foreach ($blog->translations() as $translation) {
                    $eloquentBlog->translations()->create([
                        'lang' => $translation->lang(),
                        'title' => $translation->title(),
                        'content' => $translation->content()
                    ]);
                }
            }
        });
    }

    public function delete(int $id): void
    {
        $eloquentBlog = $this->model->find($id);
        if ($eloquentBlog) {
            $eloquentBlog->delete();
        }
    }

    public function getAll(): array
    {
        $blogs = $this->model->with('translations')->get();

        return $blogs->map(function ($eloquentBlog) {
            return $this->toDomainEntity($eloquentBlog);
        })->toArray();
    }

    public function getAllByLang(string $lang): array
    {
        $blogs = $this->model->with(['translations' => function ($query) use ($lang) {
            $query->where('lang', $lang);
        }])->get();

        return $blogs->map(function ($eloquentBlog) {
            return $this->toDomainEntity($eloquentBlog);
        })->toArray();
    }

    /**
     * Convierte un modelo Eloquent a entidad de dominio
     */
    private function toDomainEntity($eloquentBlog): Blog
    {
        $translations = $eloquentBlog->translations->map(function ($t) {
            return new BlogTranslation(
                $t->lang,
                $t->title,
                $t->content,
                $t->slug,
                $t->id
            );
        })->toArray();

        return new Blog(
            $eloquentBlog->category_code,
            $eloquentBlog->status,
            $eloquentBlog->user_id,
            $eloquentBlog->image,
            $eloquentBlog->writer,
            $eloquentBlog->views,
            $eloquentBlog->published_at,
            $eloquentBlog->notification_sent_at,
            $translations,
            $eloquentBlog->id
        );
    }
}
